server:
  port: 8082
spring:
  application:
    name: InventoryManagement
  datasource:
    url: jdbc:mysql://localhost:3306/inv_mgt
    username: root
    password: Warlock@19
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect